import type { CasinoVenue } from "../casino-guide/venue-model";

/**
 * 店舗の営業時間・稼働ゲーム・最低額は当日変動が大きいため固定値にしない。
 * 住所・交通・URLを更新した場合は verifiedAt も更新する。
 */
export const MACAU_CASINO_VENUES = [
  {
    id: "venetian",
    number: "01",
    shortName: "The Venetian",
    matrixName: "Venetian",
    name: "The Venetian Macao",
    titleLines: ["The Venetian", "Macao"],
    eyebrow: "CENTRAL COTAI",
    area: "コタイ中心部",
    mapSummary: "中央・初回でも見つけやすい",
    lat: 22.1487,
    lng: 113.5607,
    recommended: true,
    airport: false,
    badge: "初回の基準店",
    lead: "コタイ中心部の大型複合リゾート。運河・飲食・買物と同じ施設内で完結しやすく、最初の1店舗として比較の基準にしやすい候補です。",
    comparison: {
      use: "初回・大型店を体験",
      tables: "バカラ中心／当日確認",
      machines: "スロット・電子卓／当日確認",
      trait: "大型・運河・買物",
      access: "コタイ西駅側・徒歩導線あり",
    },
    facts: [
      { label: "向く人", value: "マカオらしい大型リゾートとカジノを一度に見たい人。ホテルが周辺なら移動負担も抑えやすい" },
      { label: "ゲーム選び", value: "稼働ゲームと最低額はフロア表示を優先。最初に一周して、無理のないMinの卓だけを候補にする" },
      { label: "施設", value: "ショップ、レストラン、運河エリアを併設。プレイ前後の待合場所を決めやすい" },
      { label: "帰り", value: "深夜は無料シャトル終了後を想定し、ホテルまで徒歩圏外ならタクシー乗り場を先に確認" },
      { label: "住所", value: "Estrada da Baía de N. Senhora da Esperança, s/n, Taipa, Macao" },
    ],
    fit: "ホテルがVenetian・Londoner・Parisian周辺なら第一候補。広いので、集合場所と出口名を入場時に共有します。",
    links: [
      { label: "施設公式", href: "https://www.venetianmacao.com/" },
      { label: "公式連絡先・住所", href: "https://www.venetianmacao.com/hotel/about-us/contact-us.html" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=The+Venetian+Macao" },
    ],
    verifiedAt: "2026-09-17",
  },
  {
    id: "galaxy",
    number: "02",
    shortName: "Galaxy Macau",
    matrixName: "Galaxy",
    name: "Galaxy Macau",
    titleLines: ["Galaxy", "Macau"],
    eyebrow: "WEST COTAI",
    area: "コタイ西側",
    mapSummary: "西側・深夜の移動手段が比較的豊富",
    lat: 22.1493,
    lng: 113.5534,
    recommended: true,
    airport: false,
    badge: "帰路を組みやすい候補",
    lead: "複数ホテルと飲食を抱える大型リゾート。公式シャトル網が詳しく公開され、Andaz Macau便は深夜2時まで案内されているため、宿との位置関係が合えば帰路を設計しやすい候補です。",
    comparison: {
      use: "帰路と休憩を重視",
      tables: "バカラ中心／当日確認",
      machines: "スロット・電子卓／当日確認",
      trait: "ホテル群・飲食・シャトル",
      access: "Crystal／Diamond Lobbyを確認",
    },
    facts: [
      { label: "向く人", value: "Galaxy・Andaz・Broadway周辺の宿泊者。食事後そのまま1施設で夜を完結したい人" },
      { label: "シャトル", value: "路線ごとに乗り場と最終時刻が異なる。深夜2時までの案内はAndaz Macau連絡便で、全方面共通ではない" },
      { label: "待合", value: "Crystal LobbyとDiamond Lobbyを混同しない。別行動する場合はロビー名まで集合場所に指定" },
      { label: "帰り", value: "宿がシャトル対象外ならタクシーを基本にする。翌朝のチェックアウトを優先して0:30終了" },
      { label: "住所", value: "Estrada da Baia de Nossa Senhora da Esperanca, s/n, Cotai, Macau" },
    ],
    fit: "ホテルがコタイ西側なら最有力。無料バスは路線名・ロビー名・最終便を当日公式ページで再確認します。",
    links: [
      { label: "交通・シャトル公式", href: "https://www.galaxymacau.com/getting-here/" },
      { label: "施設公式", href: "https://www.galaxymacau.com/" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=Galaxy+Macau" },
    ],
    verifiedAt: "2026-09-17",
  },
  {
    id: "wynn-palace",
    number: "03",
    shortName: "Wynn Palace",
    matrixName: "Wynn",
    name: "Wynn Palace",
    titleLines: ["Wynn", "Palace"],
    eyebrow: "EAST COTAI",
    area: "コタイ東側",
    mapSummary: "東側・落ち着いた高級感",
    lat: 22.1478,
    lng: 113.5684,
    recommended: false,
    airport: false,
    badge: "雰囲気重視",
    lead: "パフォーマンスレイクに面した東コタイのリゾート。落ち着いた雰囲気を優先し、カジノ以外の夜景体験も合わせたい場合の候補です。",
    comparison: {
      use: "雰囲気・夜景を重視",
      tables: "バカラ中心／当日確認",
      machines: "スロット・電子卓／当日確認",
      trait: "高級感・湖・SkyCab",
      access: "コタイ東駅側・南入口",
    },
    facts: [
      { label: "向く人", value: "混雑感より空間とサービスの雰囲気を重視する人。東コタイ側のホテル宿泊者" },
      { label: "夜の体験", value: "SkyCabは曜日で最終時刻が異なる。カジノ開始前に乗るなら公式営業時間を当日確認" },
      { label: "シャトル", value: "公式無料便は方面ごとに概ね21〜23時台で終了。21:30以降のプレイ後はタクシー前提が安全" },
      { label: "乗り場", value: "公式案内ではシャトル乗り場は南入口。古い案内の東入口と取り違えない" },
      { label: "住所", value: "Avenida da Nave Desportiva, Cotai, Macau" },
    ],
    fit: "ホテルがWynn Palace・MGM・City of Dreams側なら候補。帰路の無料バスを当てにしすぎない運用にします。",
    links: [
      { label: "交通・シャトル公式", href: "https://www.wynnresortsmacau.com/en/wynn-palace/shuttle-bus" },
      { label: "施設公式", href: "https://www.wynnresortsmacau.com/en/wynn-palace" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=Wynn+Palace+Macau" },
    ],
    verifiedAt: "2026-09-17",
  },
  {
    id: "mgm-cotai",
    number: "04",
    shortName: "MGM COTAI",
    matrixName: "MGM",
    name: "MGM COTAI",
    titleLines: ["MGM", "COTAI"],
    eyebrow: "EAST COTAI",
    area: "コタイ東側",
    mapSummary: "東側・アートと現代的空間",
    lat: 22.1484,
    lng: 113.5703,
    recommended: false,
    airport: false,
    badge: "アート・現代性重視",
    lead: "大型デジタル空間Spectacleとアートを組み合わせた東コタイのリゾート。ゲームだけでなく施設デザインも楽しみたい場合に向きます。",
    comparison: {
      use: "アートと合わせる",
      tables: "バカラ中心／当日確認",
      machines: "スロット・電子卓／当日確認",
      trait: "現代的・アート・Spectacle",
      access: "コタイ東側・タクシーが明快",
    },
    facts: [
      { label: "向く人", value: "MGMや東コタイ側の宿泊者。フロア以外のアート・デジタル空間も見たい人" },
      { label: "ゲーム選び", value: "最低額と稼働卓は現地表示を確認。予算に合わなければ見学で終えて別施設へ追わない" },
      { label: "交通", value: "港珠澳大橋方面の公式シャトルは23:30頃までの案内があるが、宿への帰着には使えるとは限らない" },
      { label: "帰り", value: "Wynn Palaceと近いが、深夜の施設間移動より1店舗に絞ってタクシー帰着を優先" },
      { label: "住所", value: "Avenida da Nave Desportiva, Cotai, Macau" },
    ],
    fit: "ホテルがコタイ東側なら移動を短くできる候補。施設鑑賞を含めても0:30の終了線は動かしません。",
    links: [
      { label: "交通・施設公式", href: "https://www.mgm.mo/en/visit/mgm-cotai" },
      { label: "施設公式", href: "https://www.mgm.mo/en/cotai" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=MGM+COTAI+Macau" },
    ],
    verifiedAt: "2026-09-17",
  },
] as const satisfies readonly CasinoVenue[];
