import type { CasinoVenue } from "./venue-model";

// 数値・住所・URLはこのファイルだけで管理する。更新時は verifiedAt も変更する。
export const CASINO_VENUES = [
  {
    id: "paradise-city",
    number: "01",
    shortName: "Paradise City",
    matrixName: "仁川",
    name: "Paradise Casino Paradise City",
    titleLines: ["Paradise Casino", "Paradise City"],
    eyebrow: "INCHEON",
    area: "仁川空港から5分以内",
    mapSummary: "仁川・空港から5分以内",
    lat: 37.4371,
    lng: 126.4559,
    recommended: true,
    airport: true,
    badge: "空港最寄り・今回の本命",
    lead: "仁川空港から5分以内と公式案内される、韓国最大規模の外国人専用カジノ。入国後、市内へ移動する前に寄るなら4店舗で最も負担が少ない候補です。",
    comparison: {
      use: "到着直後のメイン会場",
      tables: "180台",
      machines: "332台＋144席",
      trait: "最大規模・空港・複合リゾート",
      access: "空港から5分以内・無料シャトル",
    },
    facts: [
      { label: "入場・営業", value: "24時間・年中無休。満19歳以上の外国籍旅行者が対象。パスポート必須、服装はカジュアル" },
      { label: "規模", value: "合計656設備／テーブル180台／スロット332台／ETG144席" },
      { label: "ゲーム", value: "バカラ131、BJ18、ルーレット12、その他テーブル19。4店舗でゲーム設備数が最多" },
      { label: "空港から", value: "T1は1階3Cから無料循環シャトル約20分間隔。T2は1階4Aから約60分間隔" },
      { label: "滞在環境", value: "ホテル、レストラン、スパ、アート、エンターテインメントを備える複合リゾート。到着日の時間調整にも向く" },
      { label: "住所", value: "仁川広域市 中区 永宗海岸南路321番ギル186" },
    ],
    fit: "空港からの近さと最大規模を両立。今回の到着日の第一候補。ただし、その後ソウル市内へ約1時間移動する時間は別に確保します。",
    links: [
      { label: "カジノ公式", href: "https://www.paradisecasino.co.kr/mobile/paradise-casino/incheon" },
      { label: "空港シャトル", href: "https://www.p-city.com/front/contents/pcity/location?language=EN" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=Paradise+City+Casino+Incheon" },
    ],
    verifiedAt: "2026-09-17",
  },
  {
    id: "dragon",
    number: "02",
    shortName: "Dragon City",
    matrixName: "龍山",
    name: "Seven Luck Dragon City",
    titleLines: ["Seven Luck", "Seoul Dragon City"],
    eyebrow: "YONGSAN",
    area: "龍山",
    mapSummary: "龍山・市内への動線上",
    lat: 37.53199,
    lng: 126.96216,
    recommended: false,
    airport: false,
    badge: "ソウル市内の別案",
    lead: "龍山駅近くの都心型店舗。ソウル市内へ移動した後に立ち寄る日なら、交通と食事を組み合わせやすい候補です。",
    comparison: {
      use: "市内滞在日の候補",
      tables: "55台",
      machines: "146台＋106席",
      trait: "市内動線・Casino War",
      access: "龍山駅 徒歩約3分",
    },
    facts: [
      { label: "営業", value: "24時間・年中無休。満19歳以上の外国籍旅行者が入場対象" },
      { label: "規模", value: "約3,146.96㎡／テーブル55台／マシン146台／ETG端末106席" },
      { label: "ゲーム", value: "バカラ39、BJ6、ルーレット5、Poker2、大小2、Casino War1" },
      { label: "アクセス", value: "龍山駅3番出口から徒歩約3分。新龍山駅5番出口から徒歩約10分" },
      { label: "空港から", value: "仁川空港からリムジンバスで約60〜70分。金浦空港から鉄道で約35〜45分" },
      { label: "住所", value: "龍山区チョンパロ20ギル95、コンベンションタワー5階" },
    ],
    fit: "ソウル市内の移動効率と、スロット・ETG端末の選択肢を重視する場合の候補。",
    links: [
      { label: "公式情報", href: "https://www.7luck.com/ABOT_01_01/default?GHLC_TYP=SH&sel_lang_typ=JP" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=Seven+Luck+Casino+Seoul+Dragon+City" },
    ],
    verifiedAt: "2026-09-17",
  },
  {
    id: "gangnam",
    number: "03",
    shortName: "Gangnam COEX",
    matrixName: "江南",
    name: "Seven Luck Gangnam COEX",
    titleLines: ["Seven Luck", "Gangnam COEX"],
    eyebrow: "GANGNAM",
    area: "江南",
    mapSummary: "江南・ゲーム種類を重視",
    lat: 37.51184,
    lng: 127.05761,
    recommended: false,
    airport: false,
    badge: "ゲーム種類重視の別案",
    lead: "3フロアを使うSeven Luck最大のソウル店舗。江南エリアでテーブル数とゲーム種類を優先する日に向きます。",
    comparison: {
      use: "江南滞在日の候補",
      tables: "77台",
      machines: "108台＋51席",
      trait: "Texas Hold’em・買物",
      access: "奉恩寺駅 徒歩約200m",
    },
    facts: [
      { label: "営業", value: "24時間・年中無休。満19歳以上の外国籍旅行者が入場対象" },
      { label: "規模", value: "約6,094㎡／テーブル77台／マシン108台／ETG端末51席" },
      { label: "ゲーム", value: "バカラ60、BJ8、Texas Hold’em4、Poker2、ルーレット2、大小1" },
      { label: "アクセス", value: "奉恩寺駅7番出口から約200m。三成駅5番出口から約400m" },
      { label: "周辺", value: "COEXモール、百貨店、映画館、ホテルが集中。カジノ前後の食事や買物を組みやすい" },
      { label: "住所", value: "江南区テヘラン路87ギル58、COEXコンベンション別館" },
    ],
    fit: "Texas Hold’emを含む選択肢の多さ。江南で買物や食事と組み合わせる場合の候補。",
    links: [
      { label: "公式情報", href: "https://7luck.com/ABOT_01_01/default?GHLC_TYP=KA&sel_lang_typ=JP" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=Seven+Luck+Casino+Gangnam+COEX" },
    ],
    verifiedAt: "2026-09-17",
  },
  {
    id: "walkerhill",
    number: "04",
    shortName: "Walkerhill",
    matrixName: "Walkerhill",
    name: "Paradise Walkerhill",
    titleLines: ["Paradise Casino", "Walkerhill"],
    eyebrow: "GWANGJIN",
    area: "広津",
    mapSummary: "広津・ホテル滞在型",
    lat: 37.5552,
    lng: 127.111,
    recommended: false,
    airport: false,
    badge: "ホテル滞在型の別案",
    lead: "1968年開業のホテル併設型。空港到着日の動線からは外れますが、施設規模と滞在環境を重視する別日に向きます。",
    comparison: {
      use: "ホテル滞在日の候補",
      tables: "114台",
      machines: "121台＋84席",
      trait: "ホテル・VIP環境",
      access: "駅から無料シャトル",
    },
    facts: [
      { label: "入場", value: "外国人専用。熟練ディーラーと多言語対応スタッフを公式案内" },
      { label: "規模", value: "合計319設備／テーブル114台／スロット121台／ETG84席" },
      { label: "ゲーム", value: "バカラ86、BJ8、ルーレット5、その他テーブル15。VIP・VVIPエリアあり" },
      { label: "アクセス", value: "江辺駅または広ナル駅からホテル無料シャトル。公式案内は約10分間隔" },
      { label: "周辺", value: "Grand Walkerhill Seoul内。漢江と峨嵯山に近く、ホテル滞在と合わせやすい" },
      { label: "住所", value: "広津区広壮洞サン21、Walkerhill Hotel" },
    ],
    fit: "施設規模とホテルサービス。移動効率より滞在体験を優先する場合の候補。",
    links: [
      { label: "公式情報", href: "https://www.paradisecasino.co.kr/mobile/paradise-casino/walkerhill?lang=en" },
      { label: "Google Maps", href: "https://www.google.com/maps/search/?api=1&query=Paradise+Casino+Walkerhill" },
    ],
    verifiedAt: "2026-09-17",
  },
] as const satisfies readonly CasinoVenue[];
